package me.abolfazl.nmock.utils.response.exceptions

import androidx.annotation.StringDef

const val EXCEPTION_TIMEOUT = "TIMEOUT_EXCEPTION"
const val EXCEPTION_UNKNOWN = "UNKNOWN_EXCEPTION"
const val EXCEPTION_COORDINATE_PARSE_ERROR = "COORDINATE_PARSE_ERROR_EXCEPTION"
const val EXCEPTION_API_KEY_ERROR = "API_KEY_EXCEPTION"
const val EXCEPTION_LIMIT_EXCEEDED = "LIMIT_EXCEEDED_EXCEPTION"
const val EXCEPTION_INSERTION_ERROR = "INSERTION_ERROR"
const val EXCEPTION_FORCE_CLOSE = "FORCE_CLOSE_EXCEPTION"
const val EXCEPTION_DATABASE_GETTING_ERROR = "DATABASE_ERROR_EXCEPTION"
const val EXCEPTION_SPEED_ERROR = "SPEED_ERROR_EXCEPTION"
const val EXCEPTION_COORDINATORS_ERROR = "COORDINATORS_ARE_NULL_EXCEPTION"

@StringDef(
    EXCEPTION_TIMEOUT,
    EXCEPTION_UNKNOWN,
    EXCEPTION_COORDINATE_PARSE_ERROR,
    EXCEPTION_API_KEY_ERROR,
    EXCEPTION_LIMIT_EXCEEDED,
    EXCEPTION_INSERTION_ERROR,
    EXCEPTION_FORCE_CLOSE,
    EXCEPTION_DATABASE_GETTING_ERROR,
    EXCEPTION_SPEED_ERROR,
    EXCEPTION_COORDINATORS_ERROR
)
annotation class ExceptionType()
